theme: minima
title: Sunil Joshi
author: GitHub User
email: chelamalasettyjoshi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About me!

# social links
twitter_username: joshi_twitter # DO NOT include the @ character, or else the build will fail!
github_username:  joshi_git # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
